In [2]:
import pandas as pd

In [ ]:
## series
## panda series is a one dimensional array like object can hold any data type ot is similar to a colum in a table.

In [10]:
data=[1,2,3,4,5]
series=pd.Series(data)
print("series:\n",series)

series:
 0    1
1    2
2    3
3    4
4    5
dtype: int64

In [11]:
print(type(series))

<class 'pandas.Series'>

In [13]:
## create a series from dict
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [15]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index)

a    10
b    20
c    30
dtype: int64

In [16]:
data=[10,20,30]
index=['a','b','c']
pd.Series(index,data)

10    a
20    b
30    c
dtype: str

In [22]:
## data frame
## create a dataframe from a dict of list
data={
    'Name':['prajwal','kiran','darshan'],
    'Age':[23,34,12],
    'city':['hassan','bng','ark']

}

In [23]:
df=pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age    city
0  prajwal   23  hassan
1    kiran   34     bng
2  darshan   12     ark
<class 'pandas.DataFrame'>

In [24]:
import numpy as np

In [26]:
np.array(df)

array([['prajwal', 23, 'hassan'],
       ['kiran', 34, 'bng'],
       ['darshan', 12, 'ark']], dtype=object)

In [35]:
## create a dataframe  from list of dict
data=[
    {'Name':'prajwal','age':23,'city':'hassan'},
    {'Name':'kiran','age':22,'city':'bng'},
    {'Name':'darshan','age':24,'city':'ark'},
    {'Name':'chandu','age':26,'city':'mys'},
    {'Name':'pavan','age':21,'city':'ckm'},
]

In [37]:
df=pd.DataFrame(data)
print(df)
print(type(df))

      Name  age    city
0  prajwal   23  hassan
1    kiran   22     bng
2  darshan   24     ark
3   chandu   26     mys
4    pavan   21     ckm
<class 'pandas.DataFrame'>

In [40]:
df=pd.read_csv('sales_data.csv')

In [ ]:
df.head(5) ## first 5

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [ ]:
df.tail(5) ## last 5

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [43]:
## accessing data from data
data={
    'Name':['prajwal','kiran','darshan'],
    'Age':[23,34,12],
    'city':['hassan','bng','ark']

}

In [46]:
df=pd.DataFrame(data)
print(df)

      Name  Age    city
0  prajwal   23  hassan
1    kiran   34     bng
2  darshan   12     ark

In [47]:
df['Name']

0    prajwal
1      kiran
2    darshan
Name: Name, dtype: str

In [51]:
df.loc[0] ## row index

Name    prajwal
Age          23
city     hassan
Name: 0, dtype: object

In [52]:
df.iloc[0]

Name    prajwal
Age          23
city     hassan
Name: 0, dtype: object

In [57]:
## accesing a specified element
df['Name']

0    prajwal
1      kiran
2    darshan
Name: Name, dtype: str

In [58]:
df

      Name  Age    city
0  prajwal   23  hassan
1    kiran   34     bng
2  darshan   12     ark

In [60]:
df.at[0,'Age']

np.int64(23)

In [61]:
df.at[0,'Name']

'prajwal'

In [62]:
df.at[1,'Name']

'kiran'

In [63]:
df.iat[2,2]

'ark'

In [64]:
df

      Name  Age    city
0  prajwal   23  hassan
1    kiran   34     bng
2  darshan   12     ark

In [65]:
## data manipulation with dataframe
df

      Name  Age    city
0  prajwal   23  hassan
1    kiran   34     bng
2  darshan   12     ark

In [ ]:
##adding a cloum
df['Salary']=[50000,25000,45000]

In [67]:
df

      Name  Age    city  Salary
0  prajwal   23  hassan   50000
1    kiran   34     bng   25000
2  darshan   12     ark   45000

In [ ]:
## remove a cloun
df.drop('Salary',axis=1) ## drop is a temparvery operation

      Name  Age    city
0  prajwal   23  hassan
1    kiran   34     bng
2  darshan   12     ark

In [71]:
df

      Name  Age    city  Salary
0  prajwal   23  hassan   50000
1    kiran   34     bng   25000
2  darshan   12     ark   45000

In [73]:
df.drop('Salary',axis=1,inplace=True)

C:\Users\win\AppData\Local\Temp\ipykernel_17360\2764232293.py:1: Pandas4Warning: The inplace keyword in DataFrame.drop is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  df.drop('Salary',axis=1,inplace=True)

In [74]:
df

      Name  Age    city
0  prajwal   23  hassan
1    kiran   34     bng
2  darshan   12     ark

In [80]:
## add age to the colum
df['Age']+1

0    26
1    37
2    15
Name: Age, dtype: int64

In [81]:
df

      Name  Age    city
0  prajwal   25  hassan
1    kiran   36     bng
2  darshan   14     ark

In [82]:
df.drop(0,inplace=True)

C:\Users\win\AppData\Local\Temp\ipykernel_17360\2452315191.py:1: Pandas4Warning: The inplace keyword in DataFrame.drop is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  df.drop(0,inplace=True)

In [83]:
df

      Name  Age city
1    kiran   36  bng
2  darshan   14  ark

In [85]:
df=pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [91]:
## display the data type of each colum
print("Data type:\n",df.dtypes)

## describe the data frame
print("Statistical summary:\n",df.describe)

## group by a column and perfrom an aggregation
grouped = df.groupby('Product Category')['Total Revenue'].mean()
print("mean value by category:\n",grouped)

Data type:
 Transaction ID        int64
Date                    str
Product Category        str
Product Name            str
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region                  str
Payment Method          str
dtype: object
Statistical summary:
 <bound method DataFrame.describe of      Transaction ID        Date Product Category  \
0             10001  2024-01-01      Electronics
1             10002  2024-01-02  Home Appliances
2             10003  2024-01-03         Clothing
3             10004  2024-01-04            Books
4             10005  2024-01-05  Beauty Products
..              ...         ...              ...
235           10236  2024-08-23  Home Appliances
236           10237  2024-08-24         Clothing
237           10238  2024-08-25            Books
238           10239  2024-08-26  Beauty Products
239           10240  2024-08-27           Sports

                                        Product Name  Units Sold  Unit Price  \
0                                      iPhone 14 Pro           2      999.99
1                                   Dyson V11 Vacuum           1      499.99
2                                   Levi's 501 Jeans           3       69.99
3                                  The Da Vinci Code           4       15.99
4                            Neutrogena Skincare Set           1       89.99
..                                               ...         ...         ...
235  Nespresso Vertuo Next Coffee and Espresso Maker           1      159.99
236                        Nike Air Force 1 Sneakers           3       90.00
237           The Handmaid's Tale by Margaret Atwood           3       10.99
238             Sunday Riley Luna Sleeping Night Oil           1       55.00
239                       Yeti Rambler 20 oz Tumbler           2       29.99

     Total Revenue         Region Payment Method
0          1999.98  North America    Credit Card
1           499.99         Europe         PayPal
2           209.97           Asia     Debit Card
3            63.96  North America    Credit Card
4            89.99         Europe         PayPal
..             ...            ...            ...
235         159.99         Europe         PayPal
236         270.00           Asia     Debit Card
237          32.97  North America    Credit Card
238          55.00         Europe         PayPal
239          59.98           Asia    Credit Card

[240 rows x 9 columns]>
mean value by category:
 Product Category
Beauty Products     65.54750
Books               46.54825
Clothing           203.22325
Electronics        874.56025
Home Appliances    466.15400
Sports             358.16300
Name: Total Revenue, dtype: float64

In [87]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [89]:
df.columns

Index(['Transaction ID', 'Date', 'Product Category', 'Product Name',
       'Units Sold', 'Unit Price', 'Total Revenue', 'Region',
       'Payment Method'],
      dtype='str')